### ISSUE TITLE
CUI --> CONCEPT_ID for SemMedDB

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#1]
Right now for the CUI to CONCEPT_ID mapping we use UMLS, however this means we are missing RxNorm extension maps.  We could double back and just look for direct string mappings or some other ways to improve the mapping.

**Comment by cgreich** [comment]
CUI to Concept_id mapping? They are missing? I don't get it. We get all of RxNorm and give them a Concept_id.

**Comment by ericaVoss** [comment]
@cgreich ha, I can't hide any Vocabulary comments from you can it?  :)  I was talking about drugs that are in the Extensions, based on how I'm pulling out of UMLS to go from CUI --> RxNorm I'd be missing those OMOP generated maps.

**Comment by cgreich** [comment]
Because it sends a notification to my inbox! :)

Ok, but what are you mapping from? RxNorm CUIs are equal to concept_codes, but RxNorm Extension concepts have no CUI. What are you trying to do?

**Comment by ericaVoss** [comment]
Mapping created using USAGI
