### ISSUE TITLE
Can I use your project in order to get UMLS similarity/relatedness?

### ISSUE THREAD

**Issue by yonatanbitton** [OHDSI/CommonEvidenceModel#104]
Hello. I'm trying to get UMLS similarity/relatedness.

I'm trying to use this code:
https://metacpan.org/pod/UMLS::Similarity

In a python environment.
I've found this link: https://github.com/OHDSI/KnowledgeBase/blob/master/LAERTES/concept-similarity/runUMLSSimilarity.py
Which refers to this project.

I don't understand if it's possible to use this project in order to get UMLS similarity.
I need very simple functionality: given two UMLS terms: (for example 'insulin' and 'diabetes') I want to know their relatedness and similarity.

Thanks !

**Comment by ericaVoss** [comment]
No, we aren't using that in CEM. 

But I would talk to @rkboyce he knows more about that area.
