### ISSUE TITLE
Pentaho Data Integration server (PDI) version requirement question

### ISSUE THREAD

**Issue by konstjar** [OHDSI/CommonEvidenceModel#107]
The current version available on Pentaho website is 9.0. Can I use it instead of 7.1 as it is mentioned in documentation?

![image](https://user-images.githubusercontent.com/4144173/79049826-1750e380-7c26-11ea-96f2-c142ec0b5f46.png)

**Comment by leeevans** [comment]
Yes, you should be able to use the latest available pentaho version
