### ISSUE TITLE
Add Link out Ability

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#37]
Via a WebAPI call

**Comment by ericaVoss** [comment]
To start, I will write a query on how I would find publications for DESCENDANTS, EXACT, PARENT, and ANCESTOR.

**Comment by ericaVoss** [comment]
@anthonysena I wrote a query to find publications:
https://github.com/OHDSI/CommonEvidenceModel/blob/ftpUniverse/sandbox/PULLING_PMID_FROM_CEM_UNIFIED.sql

**Comment by ericaVoss** [comment]
@anthonysena - this now will pull you both the PMIDs for publications and all the label IDs for SPLs.

https://github.com/OHDSI/CommonEvidenceModel/blob/master/sandbox/PULLING_PMID_FROM_CEM_UNIFIED.sql

**Comment by anthonysena** [comment]
Note to self: look at how to get publication titles from NLM based on the PMID's returned from this query. Don't let this hold up the release though.

**Comment by anthonysena** [comment]
Added as part of: https://github.com/OHDSI/WebAPI/commit/ed524d7e800b9a08918771882f477e9c93cc3fa0 and https://github.com/OHDSI/Atlas/commit/844777cd470c386d525ad07b20ef44876993b94a

![bitmoji](https://render.bitstrips.com/v2/cpanel/7daa51e7-2b06-4373-a55f-7b17e269d051-911dd4db-057f-422a-acd6-b5c40427abc9-v1.png?transparent=1&palette=1&width=246)
