### ISSUE TITLE
LAERTES virtuoso semantic web server

### ISSUE THREAD

**Issue by leeevans** [OHDSI/CommonEvidenceModel#41]
What is the plan going forward for the OHDSI LAERTES virtuoso semantic web server?

Do we need to build a new CEM workflow to create a compatible semantic (RDF) database extract from CEM and load that data into Virtuoso (replacing the current LAERTES data load), or just shut down the Virtuoso server as part of the LAERTES sunset activities?

**Comment by ericaVoss** [comment]
@rkboyce I would think this question is for you.

**Comment by rkboyce** [comment]
There is no usage of RDF by anyone AFIK. I can serve that from Pitt's implementation. So, feel free to shut it down. The knowledgebase explorer will need to be taken down too. Might want to have some info the form of a custom 404 that explains the migration to CEM and provides my email for folks interested in the RDF data view.

**Comment by ericaVoss** [comment]
We have agreed to shut it down (next week).
@leeevans to take a snap shot prior to shutting down.

**Comment by ericaVoss** [comment]
@leeevans has this been completed?  I believe it has.

**Comment by leeevans** [comment]
@ericaVoss yes it's been completed.
