### ISSUE TITLE
postProcessingNegativeControlsExport

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#44]
Create export function that:
1) exports data tables (CEM_EVIDENCE, LU_ tables)
2) Generate a DDL for the tables exported
3) add the two required tables for ATLAS (EVIDENCE_JOB, NC_RESULT)

Output is data tables and DDL.

**Comment by ericaVoss** [comment]
Asked @leeevans if we export via R it is fine.  

One problem we need to address is what Vocab needs to go with the Export

Erica Action:
What Vocabularies do we actually need form OMOP Vocab (processing Vocab, export Vocab)

Sharing data:
--Host via OHDSI Google Drive (with Synpuf CDM)

**Comment by ericaVoss** [comment]
- CEM_UNIFIED
- NC_LU_BROAD_CONCEPTS
- NC_LU_CONCEPT_UNIVERSE
- NC_LU_DRUG_INDUCED_CONDITIONS
- NC_LU_PREGNANCY
- SOURCE
- vocabulary.CONCEPT (Erica - think about what is needed to be shared to work, I think only standard concepts)
- vocabulary.CONCEPT_ANCESTOR
- vocabulary.CONCEPT_RELATIONSHIP
- translated.AEOLUS
- translated.MEDLINE_WINNENBURG
- translated.SPLICER

**Comment by ericaVoss** [comment]
UTF8 encoding on export

**Comment by leeevans** [comment]
Created concept_export, concept_ancestor_export, and concept_relationship views in CEM vocabulary schema to specify the subset of vocabulary concepts to export.

**Comment by leeevans** [comment]
This issue is complete.
