### ISSUE TITLE
omop_vocab_load kettle job todos

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/CommonEvidenceModel#48]
Hi, I ran through this kettle job with some stops and starts. These todos are potential enhancements to help others deploy at their location. These could be in the form of notes or job tasks:

1) schema staging_vocabulary needs created under cem if this is the first run

2) The vocab tables for the CDM need to be loaded into staging_vocabulary if this is the first run

Thanks,
-R

**Comment by ericaVoss** [comment]
@rkboyce I think we can close this issue as @leeevans already created a STAGING_VOCABULARY.  Please re-open if that is not the case.
