### ISSUE TITLE
Drugs to get rid of

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#49]
967823 | Sodium Chloride
-- | --

19049105 | Potassium Chloride
-- | --

**Comment by cgreich** [comment]
Yeah. Talk to Anna. It's not that simple.

**Comment by ericaVoss** [comment]
Followed up on forums but for right now I'll just manually remove these two.
http://forums.ohdsi.org/t/broad-drugs/4219
