### ISSUE TITLE
[WEB API PATCH] Indications / Contraindications

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#58]
Added in Contraindications to the Indications column and renamed the column as such.

Commit:
https://github.com/OHDSI/CommonEvidenceModel/commit/128522d218e2fbeeeea28f8cdda474ef6a42bcc9

- Missing UPPER() on line 11, this was a bug.  Also added IND/CI on line 21 & Line 47.  Added the UPPER back in Line 40, 45
postProcessingNegativeControls/inst/sql/sql_server/findDrugIndications.sql
- Column rename
postProcessingNegativeControls/inst/sql/sql_server/optimizeEvidence.sql 
- Column rename
postProcessingNegativeControls/inst/sql/sql_server/summarizeEvidence.sql

**Comment by ericaVoss** [comment]
Keeping this issue open for this minor fix:
https://github.com/OHDSI/WebAPI/issues/391

**Comment by anthonysena** [comment]
Note to self: look at the commit referenced above to ensure we're in sync with WebAPI SQL Files.

**Comment by anthonysena** [comment]
Fixed in: https://github.com/OHDSI/Atlas/commit/844777cd470c386d525ad07b20ef44876993b94a

![bitmoji](https://render.bitstrips.com/v2/cpanel/4f86bb1d-c23d-4dd7-b907-64d43afc116f-911dd4db-057f-422a-acd6-b5c40427abc9-v1.png?transparent=1&palette=1&width=246)
