### ISSUE TITLE
Redevelop R Script for Loading CONCEPT_UNIVERSE

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#59]
In the Negative Prep EVIDENCE.NC_LU_CONCEPT_UNIVERSE.

An approach is to generate this at the raw data update step that Lee does.  I could generate the data and then provide the large file to Lee.

**Comment by ericaVoss** [comment]
@leeevans how do you bulk load to the server?  Maybe I can do the same?  DatabaseConnector::insertTable() takes too long.

**Comment by alondhe** [comment]
For which db platform?

**Comment by ericaVoss** [comment]
Happy Birthday @alondhe :1st_place_medal:  

I was trying to load to the OHDSI Postgres, it ran for 36 hours and we gave up and @leeevans loaded some other way.

**Comment by ericaVoss** [comment]
Can I run that from R?  Wondering if I need super permissions to run, not sure what I have.  Do you have an example?

**Comment by ericaVoss** [comment]
Erica to write out the file to an FTP server for the processing.  Lee to send the location.

**Comment by ericaVoss** [comment]
Completed in branch [ftpUniverse](https://github.com/OHDSI/CommonEvidenceModel/tree/ftpUniverse).  Waiting for confirmation from Lee that the file looks okay.
