### ISSUE TITLE
Pentaho instructions

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/CommonEvidenceModel#63]
I am trying to run informationPrep and the CTD job.

Please provide 1 paragraph of documentation.

e.g.,

Can I use the 30 day trial? http://www.pentaho.com/download 

I am assuming .kjb file is the Pentaho file.

**Comment by leeevans** [comment]
@vojtechhuser 

The 30 day trial will work or you can download the community edition.  It looks like Hitachi made changes to the pentaho web site but they should still reference a community edition somewhere.

The readme page below has the pentaho data integration requirements/version: 
https://github.com/OHDSI/CommonEvidenceModel/tree/master/informationPrep

There is a paragraph of instructions at the bottom of the CTD readme page (some familiarity with the pentaho data integration tool is assumed):

https://github.com/OHDSI/CommonEvidenceModel/tree/master/informationPrep/jobs/CTD
