### ISSUE TITLE
ATLAS and CEM Results

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#78]
When CEM produces results it should generate a results schema in CEM.RESULTS.  Right now CEM is writing  to writing to WEBAPI database.

**Comment by ericaVoss** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/1c032d8e-be0f-44c7-adb6-3c2887c7b9c6-f9de47cd-e918-4b50-831d-d887a6386e5f-v1.png?transparent=1&palette=1&width=246)

**Comment by ericaVoss** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/3f8aba80-1d22-479d-a4cb-e20860bf17f8-f9de47cd-e918-4b50-831d-d887a6386e5f-v1.png?transparent=1&palette=1&width=246)

**Comment by anthonysena** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/f10a932e-9fe7-4022-ac06-533f66ffb652-911dd4db-057f-422a-acd6-b5c40427abc9-v1.png?transparent=1&palette=1&width=246)

Fixed as of: https://github.com/OHDSI/WebAPI/commit/ed524d7e800b9a08918771882f477e9c93cc3fa0
