### ISSUE TITLE
Too Broad

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#8]
Let the Too Broad concepts run for DRUGS too.

967823 | Sodium Chloride
-- | --
19049105 | Potassium Chloride

Add more conditions:

CONCEPT_ID | CONCEPT_NAME
-- | --
444239 | Postprocedural state finding
136237 | Cardiovascular system problem
4319325 | Acquired deformity of trunk
4168222 | Intra-abdominal and pelvic   swelling, mass and lump
138255 | Abnormal cardiovascular function
137967 | Muscle, ligament and fascia   disorders
195603 | Vulval and/or perineal   noninflammatory disorders
4164707 | Canceled operative procedure

**Comment by cgreich** [comment]
@ericaVoss:

Can you explain a little more?

**Comment by ericaVoss** [comment]
When building negative controls there are some concepts we don't want to include.

**Comment by cgreich** [comment]
Where? And right now you have those two?

**Comment by ericaVoss** [comment]
I have a bunch to ignore when building negative control sets, but mostly broad conditions.

**Comment by cgreich** [comment]
Why is it an issue here, then?

**Comment by ericaVoss** [comment]
Because building negative controls is part of the processing in CEM

**Comment by cgreich** [comment]
Ask @dimshitc. He might have a good list.

**Comment by ericaVoss** [comment]
Started a conversation:
http://forums.ohdsi.org/t/finding-broad-concepts/3627
