### ISSUE TITLE
STAGING_AUDIT

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#83]
Create a staging_audit schema.

the SOURCE table should live here.  Lee's processing can automatically update this table.  Erica's CEM processing should pull from there.

Current CSV
https://github.com/OHDSI/CommonEvidenceModel/blob/master/evidenceProcessingClean/extras/source.csv

**Comment by leeevans** [comment]
new staging_audit.source schema/table created and loaded with current rows in evidence.source table

**Comment by leeevans** [comment]
re-opened for @ericaVoss to update CEM process to pull from the new table

**Comment by ericaVoss** [comment]
@leeevans could you open up permissions to this table?  Thank you!  I think the owner is `ecmadmin`, could this be altered to `rw_grp`?

```
SELECT *
FROM STAGING_AUDIT.SOURCE

ERROR:  permission denied for relation source
********** Error **********

ERROR: permission denied for relation source
SQL state: 42501
```

**Comment by leeevans** [comment]
@ericaVoss try it now

**Comment by ericaVoss** [comment]
@leeevans works now!  Thank you!
