### ISSUE TITLE
"Obtaining Negative Controls from ATLAS" Link

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CommonEvidenceModel#94]
On the "Explore Evidence" tab, there is "Obtaining Negative Controls from ATLAS".  Could this link to this URL instead?
https://github.com/OHDSI/CommonEvidenceModel/wiki/Negative-Controls-In-ATLAS

**Comment by anthonysena** [comment]
This has been updated as part of the Atlas commit: https://github.com/OHDSI/Atlas/commit/844777cd470c386d525ad07b20ef44876993b94a
