### ISSUE TITLE
examples generate .java content

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/CommonEvidenceModel#97]
when I try these calls 

Information on all evidence services [GET] | http://api.ohdsi.org/WebAPI/evidence/CS1/info
-- | --
Evidence by drug concept id (any level in the drug hierarcchy) [GET] | http://api.ohdsi.org/WebAPI/evidence/CS1/drug/752061
Evidence by HOI concept id [GET] | http://api.ohdsi.org/WebAPI/evidence/CS1/hoi/320073
Evidence by concatenated drug and HOI concept id [GET] | http://api.ohdsi.org/WebAPI/evidence/CS1/drughoi/19059744-381591
Evidence with any OHDSI concept id representing an RxNorm or SNOMED concept | http://api.ohdsi.org/WebAPI/evidence/CS1/7520

I get

![image](https://user-images.githubusercontent.com/7526119/45703908-9ada4980-bb43-11e8-969e-312074c4fd6a.png)

What am I doing wrong?

**Comment by leeevans** [comment]
@vojtechhuser @ericaVoss @anthonysena  I updated the example URLs to correct this issue
